// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aotowjfwiucuwpapaplu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvdG93amZ3aXVjdXdwYXBhcGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDY1NDAsImV4cCI6MjA2MTc4MjU0MH0.TkPBQHME7jVVH368u1PkdrX-3EGseXMXRW6V2pggwkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);